<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IABLR-LT155" name="Runner.RunCuke" tests="2" failures="1" timestamp="7 Nov 2019 07:46:40 GMT" time="3.705" errors="0">
  <testcase name="runScenario" time="2.747" classname="Runner.RunCuke"/>
  <testcase name="runScenario" time="0.958" classname="Runner.RunCuke">
    <failure type="java.lang.AssertionError" message="expected [21312] but found [Invalid API Key provided: sk_test_***************************alid]">
      <![CDATA[java.lang.AssertionError: expected [21312] but found [Invalid API Key provided: sk_test_***************************alid]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at StepDefnitions.Create_Customer_Test.the_response_contains_the_message(Create_Customer_Test.java:158)
	at âœ½.the response contains the message "21312"(./src/test/Feature_Files/Customer_API.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Runner.RunCuke -->
